---
# Set default variables
- import_tasks: set-default-variables.yml

- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Streisand common packages
  apt:
    package: "{{ streisand_common_packages }}"

- name: Purge unneeded services
  apt:
    package: "{{ streisand_unneeded_packages }}"
    state: "absent"
    purge: yes
    autoremove: yes

- name: Docker pull
  shell: "docker pull riftbit/3proxy"

- name: Docker deoloy
  shell: "docker run --name 3proxy -d -p 3128:3128 --restart always --env PROXY_LOGIN=passmefast --env PROXY_PASSWORD=aviscousSecurity riftbit/3proxy
"

- name: Post this proxy to database
  uri:
    url: http://dashboard.passmefast.co.uk:4466
    method: POST
    body: '{"query": "mutation CreateProxy($proxy: String!, $stopUseUntil: DateTime $ip: String!, $type: String, $blockCount: Int, $username: String, $password: String, $lastUsedAt: DateTime) { createProxy(data:{proxy: $proxy, stopUseUntil:$stopUseUntil ip: $ip, type: $type, blockCount:$blockCount, lastUsedAt: $lastUsedAt, username: $username, password: $password}){ip} }","variables": { "proxy": "http://{{streisand_ipv4_address}}:3128", "username": "passmefast", "password": "aviscousSecurity", "ip":"{{streisand_ipv4_address}}", "type":"digitalocean", "blockCount":0, "lastUsedAt": "2019-05-25", "stopUseUntil": "2019-05-25"}}'
    body_format: json
    headers:
      Content-Type: "application/json"