---
# Set default variables
- import_tasks: set-default-variables.yml

- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Streisand common packages
  apt:
    package: "{{ streisand_common_packages }}"

- name: Purge unneeded services
  apt:
    package: "{{ streisand_unneeded_packages }}"
    state: "absent"
    purge: yes
    autoremove: yes

- name: Docker pull
  shell: "docker pull chenhw2/brook"

- name: Docker deoloy
  shell: "docker run -d -e 'ARGS=socks5 -l :9999 -i {{ streisand_ipv4_address }}' -p 9999:9999/tcp -p 9999:9999/udp chenhw2/brook"

- name: Post this proxy to database
  uri:
    url: http://dashboard.passmefast.co.uk:4466
    method: POST
    body: '{"query": "mutation CreateProxy($proxy: String!, $stopUseUntil: DateTime $ip: String!, $type: String, $blockCount: Int, $lastUsedAt: DateTime) { createProxy(data:{proxy: $proxy, stopUseUntil:$stopUseUntil ip: $ip, type: $type, blockCount:$blockCount, lastUsedAt: $lastUsedAt}){ip} }","variables": { "proxy": "socks5://{{streisand_ipv4_address}}:9999", "username": "passmefast", "password": "aviscousSecurity", "ip":"{{streisand_ipv4_address}}", "type":"digitalocean", "blockCount":0, "lastUsedAt": "2019-05-25", "stopUseUntil": "2019-05-25"}}'
    body_format: json
    headers:
      Content-Type: "application/json"