---
streisand_common_packages:
  # Ensure that Apparmor is installed
  - apparmor
  # Enables support for the HTTPS protocol in APT sources
  - apt-transport-https
  # Used to perform a system upgrade
  - aptitude
  # Used to compile Libreswan and OpenConnect Server (ocserv)
  - build-essential
  # Used to perform API requests, including the version check for
  # the Tor Browser Bundle
  - curl
  # Enables automation of programs and scripts that ask for user input
  - expect
  # Used for automatically installing security updates
  - unattended-upgrades
  # Install git for source code retrieval and use with "go get" command
  - git

# Services that are running by default but not needed by Streisand
streisand_unneeded_packages:
  - lxd
  - snapd

# By default concurrent executions of `iptables` will fail immediately if unable
# to acquire a lock. We use the `--wait` argument to instead specify a maximum
# number of seconds to wait before failing. This allows multiple services to add
# iptables rules at once. See Issue #950 for longer term ideas on how to make
# this var not required.
streisand_iptables_wait: 120


# In online documentation, we recommand a URL for people to check
# their effective IP address.

streisand_my_ip_url: https://duckduckgo.com/?q=ip+address

# We used to use Google; it has marginally better usability, but there
# are reasons not to use it.  If you're reading this, you know enough
# to make your own decision.
#
# streisand_my_ip_url: https://encrypted.google.com/search?hl=en&q=my%20ip%20address

apt_repository_retries: 10
apt_repository_delay: 20
