---
- name: Customize enabled Streisand services
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: streisand_ssh_private_key
      prompt: "Enter the path to your SSH private key, or press enter for default "
      default: "~/.ssh/id_rsa"
      private: no