---
- import_playbook: python.yml

- name: Collect diagnostics in case of error
  hosts: localhost
  gather_facts: no
  roles:
    - role: diagnostics
      when: not streisand_ci

- name: Configure the Server and install required software
# ========================================================
  hosts: streisand-host

  remote_user: "root"
  become: true

  roles:
    - common
    - ssh
    # tor-bridge is skipped in our full Ansible run on Travis CI due to
    # connectivity issues.
    - ufw
...
